##############################################################################
#
#  Configuration for MARC XML Import (Alma)
#
#  Part of https://idbugs.uzh.ch/browse/ZORA-976
#  based originally on AlephMarc import (ZORA-671)
#   
#
##############################################################################
#
# The MARC import mappings hash describes the mapping from a MARC field/subfield 
# to a method that converts the data into the given EPrints field
#

$c->{marc_import_mappings} = [
	{ 
		'marcfieldtype' => 'controlfield',
		'marcfield' => '001',
		'marcsubfield' => 'none',
		'fieldname' => 'related_url',
		'method' => 'marc2systemnumber',
	},
	{ 
		'marcfieldtype' => 'controlfield',
		'marcfield' => '008',
		'marcsubfield' => 'none',
		'fieldname' => 'language_mult',
		'method' => 'marc0082language',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '020',
		'marcsubfield' => 'a',
		'fieldname' => 'isbn',
		'method' => 'marc2isbn',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '022',
		'marcsubfield' => 'a',
		'fieldname' => 'issn',
		'method' => 'marc2issn',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '024',
		'marcsubfield' => 'a',
		'fieldname' => '',
		'method' => 'marc2doi_pmid',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '041',
		'marcsubfield' => 'a',
		'fieldname' => 'language_mult',
		'method' => 'marc0412language',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '082',
		'marcsubfield' => 'a',
		'fieldname' => 'dewey',
		'method' => 'marc2dewey',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '100',
		'marcsubfield' => 'a',
		'fieldname' => '',
		'method' => 'marc2person',
		'filter' => 'person',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '110',
		'marcsubfield' => 'a',
		'fieldname' => 'corp_creators',
		'method' => 'marc2corpcreators',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '111',
		'marcsubfield' => 'a',
		'fieldname' => 'event_title',
		'method' => 'marc2event_title',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '111',
		'marcsubfield' => 'c',
		'fieldname' => 'event_location',
		'method' => 'direct',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '111',
		'marcsubfield' => 'd',
		'fieldname' => '',
		'method' => 'marc2event_date',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '240',
		'marcsubfield' => 'a',
		'fieldname' => 'othertitles',
		'method' => 'marc2othertitles',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '245',
		'marcsubfield' => 'a',
		'fieldname' => 'title',
		'method' => 'marc2title',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '245',
		'marcsubfield' => 'b',
		'fieldname' => 'title',
		'method' => 'marc2title',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '245',
		'marcsubfield' => 'c',
		'fieldname' => '',
		'method' => 'marc245c2person',
		'filter' => 'creators',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '250',
		'marcsubfield' => 'a',
		'fieldname' => 'note',
		'method' => 'marc2note',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '250',
		'marcsubfield' => 'b',
		'fieldname' => 'note',
		'method' => 'marc2note',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '246',
		'marcsubfield' => 'a',
		'fieldname' => 'othertitles',
		'method' => 'marc2othertitles',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '260',
		'marcsubfield' => 'a',
		'fieldname' => 'place_of_pub',
		'method' => 'marc2place',
		'filter' => 'garbage',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '260',
		'marcsubfield' => 'b',
		'fieldname' => 'publisher',
		'method' => 'marc2publisher',
		'filter' => 'garbage',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '260',
		'marcsubfield' => 'c',
		'fieldname' => 'date',
		'method' => 'marc2date',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '264',
		'marcsubfield' => 'a',
		'fieldname' => 'place_of_pub',
		'method' => 'marc2place',
		'filter' => 'garbage',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '264',
		'marcsubfield' => 'b',
		'fieldname' => 'publisher',
		'method' => 'marc2publisher',
		'filter' => 'garbage',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '264',
		'marcsubfield' => 'c',
		'fieldname' => 'date',
		'method' => 'marc2date',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '300',
		'marcsubfield' => 'a',
		'fieldname' => 'pages',
		'method' => 'marc2pages',
		'filter' => 'pages',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '490',
		'marcsubfield' => 'a',
		'fieldname' => 'series',
		'method' => 'marc2series',
		'filter' => 'series',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '490',
		'marcsubfield' => 'v',
		'fieldname' => 'volume',
		'method' => 'marc2volume',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '490',
		'marcsubfield' => 'x',
		'fieldname' => 'issn',
		'method' => 'marc2issn',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '500',
		'marcsubfield' => 'a',
		'fieldname' => 'note',
		'method' => 'marc2note',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '502',
		'marcsubfield' => 'a',
		'fieldname' => 'examinerstmp',
		'method' => 'marc5022examiners',
		'filter' => 'examiners',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '502',
		'marcsubfield' => 'b',
		'fieldname' => 'type',
		'method' => 'marc2degreetype',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '502',
		'marcsubfield' => 'c',
		'fieldname' => 'institution',
		'method' => 'marc2institution',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '502',
		'marcsubfield' => 'd',
		'fieldname' => 'date',
		'method' => 'marc2date',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '505',
		'marcsubfield' => 'a',
		'fieldname' => 'note',
		'method' => 'marc2note',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '506',
		'marcsubfield' => 'a',
		'fieldname' => 'accesstmp',
		'method' => 'marc2access',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '518',
		'marcsubfield' => 'a',
		'fieldname' => 'note',
		'method' => 'marc2note',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '518',
		'marcsubfield' => 'd',
		'fieldname' => 'note',
		'method' => 'marc2note',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '518',
		'marcsubfield' => 'p',
		'fieldname' => 'note',
		'method' => 'marc2note',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '520',
		'marcsubfield' => 'a',
		'fieldname' => 'abstract',
		'method' => 'direct',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '536',
		'marcsubfield' => 'a',
		'fieldname' => 'funding_reference',
		'method' => 'marc2funding',
		'filter' => 'funding',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '546',
		'marcsubfield' => 'a',
		'fieldname' => 'note',
		'method' => 'marc2note',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '550',
		'marcsubfield' => 'a',
		'fieldname' => 'note',
		'method' => 'marc2note',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '600',
		'marcsubfield' => 'a',
		'fieldname' => 'keywords',
		'method' => 'marc2personkeywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '600',
		'marcsubfield' => 'c',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '600',
		'marcsubfield' => 'd',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '600',
		'marcsubfield' => 't',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '610',
		'marcsubfield' => 'a',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '610',
		'marcsubfield' => 'b',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '610',
		'marcsubfield' => 'g',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '610',
		'marcsubfield' => 't',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '630',
		'marcsubfield' => 'a',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '648',
		'marcsubfield' => 'a',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '650',
		'marcsubfield' => 'a',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '650',
		'marcsubfield' => 'g',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '650',
		'marcsubfield' => 'x',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '650',
		'marcsubfield' => 'y',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '650',
		'marcsubfield' => 'z',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '651',
		'marcsubfield' => 'a',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '651',
		'marcsubfield' => 'g',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '651',
		'marcsubfield' => 'x',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '653',
		'marcsubfield' => 'a',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '655',
		'marcsubfield' => 'a',
		'fieldname' => 'type',
		'method' => 'marc655a2type',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '690',
		'marcsubfield' => 'a',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '690',
		'marcsubfield' => 'd',
		'fieldname' => 'keywords',
		'method' => 'marc690d2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '691',
		'marcsubfield' => 'a',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '691',
		'marcsubfield' => '8',
		'fieldname' => 'keywords',
		'method' => 'marc2keywords',
		'filter' => 'keywords',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '700',
		'marcsubfield' => 'a',
		'fieldname' => '',
		'method' => 'marc2person',
		'filter' => 'person',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '710',
		'marcsubfield' => 'a',
		'fieldname' => 'corp_creators',
		'method' => 'marc2corpcreators',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '711',
		'marcsubfield' => 'a',
		'fieldname' => 'event_title',
		'method' => 'marc2event_title',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '711',
		'marcsubfield' => 'c',
		'fieldname' => 'event_location',
		'method' => 'direct',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '711',
		'marcsubfield' => 'd',
		'fieldname' => '',
		'method' => 'marc2event_date',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '773',
		'marcsubfield' => 't',
		'fieldname' => '',
		'method' => 'marc2hostitementry',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '787',
		'marcsubfield' => 'a',
		'fieldname' => 'note',
		'method' => 'marc2note',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '856',
		'marcsubfield' => 'u',
		'fieldname' => 'related_url',
		'method' => 'marc2url',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '900',
		'marcsubfield' => 'a',
		'fieldname' => '',
		'method' => 'marc9002examiners',
	},
	{
		'marcfieldtype' => 'datafield',
		'marcfield' => '909',
		'marcsubfield' => 'b',
		'fieldname' => 'faculty',
		'method' => 'marc2faculty',
	},
];

#
# Mapping of leader bibliographic level to type
# This mapping is coarse and in addition marcfield 655_a must be used
# 
$c->{marcbiblevel2typemap} = {
	'a' => 'book_section',
	'b' => 'article',
	'm' => 'monograph',
};

#
# Mapping of encoding level to status
#
$c->{marcencoding2statusmap} = {
	' ' => 'final',
	'1' => 'final',
	'2' => 'final',
	'3' => 'final',
	'4' => 'final',
	'5' => 'final',
	'7' => 'final',
	'8' => 'firstelectronic',
};

#
# Mapping of 100_e/100_4/700_4/700_e relator term to creator/editor/examiner field
#
$c->{marcpersonrelatormap} = {
	'Akademischer Betreuer' => 'examiners',
	'AkademischeR BetreuerIn' => 'examiners',
	'Herausgeber' => 'editors',
	'HerausgeberIn' => 'editors',
	'Verfasser' => 'creators',
	'VerfasserIn' => 'creators',
	'aut' => 'creators',
	'author' => 'creators',
	'dgs' => 'examiners',
	'editor' => 'editors',
	'edt' => 'editors',
};

#
# Person titles for removal
#
$c->{marchonorific} = [
	'Prof\.\s*',
	'PD\s*',
	'Dr\.\s*',
	'lic\.\s*',
	'dipl\.\s*',
	'phil\.\s*',
	'rer\.\s*',
	'ssc\.\s*',
	'h\.c\.\s*',
	'hc\.\s*',
	'publ\.\s*',
	'mult\.\s*',
	'dent\.\s*',
	'iur\.\s*',
	'jur\.\s*',
	'med\.\s*',
	'nat\.\s*',
	'oec\.\s*',
	'vet\.\s*',
	'DipECVPH',
];	

#
# Person name prefixes for shifting from given to family name
# Used with field 100_c, 245_c, 700, ..
#
$c->{marcshiftnameparts} = [
	'(.*?)\s<<(.*?)>>',
	'(.*?)\s(aus\sder.*)$',
	'(.*?)\s(da\s?.*)$',
	'(.*?)\s(de\s?.*)$',
	'(.*?)\s(della\s?.*)$',
	'(.*?)\s(van\s?.*)$',
	'(.*?)\s(von\s?.*)$',
];

#
# Dissertation note (502_a) analysis rules
# institution => 'guess' means that institution can be taken from regex $1
#
$c->{marcdissertationnote} = [
	{
		pattern => '^Cumulative\sthesis\s(.*?),\s\d{4}',
		type => 'dissertation',
		subtype => 'cumulative',
		institution => 'guess',
		faculty => '',
	},
	{
		pattern => '^Kumulative\sDiss\.\s(.*?),\s\d{4}',
		type => 'dissertation',
		subtype => 'cumulative',
		institution => 'guess',
		faculty => '',
	},
	{
		pattern => '^Tesi\s(.*?),',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'guess',
		faculty => '',
	},
	{
		pattern => '^Thesis\s(.*?),',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'guess',
		faculty => '',
	},
	{
		pattern => '^Th\x{e8}se\s(.*?),',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'guess',
		faculty => '',
	},
	{
		pattern => '^Diss\.\sMath',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'University of Zurich',
		faculty => 'science',
	},
	{
		pattern => '^Diss\.\sphil\.\sI\sUniv\.\sZ\x{fc}rich',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'University of Zurich',
		faculty => 'arts',
	},
	{
		pattern => '^Diss\.\sphil\.\sUniv\.\sZ\x{fc}rich',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'University of Zurich',
		faculty => 'arts',
	},
	{
		pattern => '^Diss\.\stheol\.\sUniv\.\sZ\x{fc}rich',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'University of Zurich',
		faculty => 'theology',
	},
	{
		pattern => 'Diss\.\svet\.\smed\.\s\sUniv\.\sZ\x{fc}rich',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'University of Zurich',
		faculty => 'vetsuisse',
	},
	{
		pattern => 'Abhandlung.*?Doktorw\x{fc}rde.*?Philosophischen\sFakult\x{e4}t.*?Universit\x{e4}t\sZ\x{fc}rich',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'University of Zurich',
		faculty => 'arts',
	},
	{
		pattern => '^Diss\.,?\sUniv\.\sZ\x{fc}rich',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'University of Zurich',
		faculty => '',
	},
	{
		pattern => '^Diss\.,?\sVetsuisse',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'University of Zurich',
		faculty => 'vetsuisse',
	},
	{
		pattern => '^Diss\.,?\s(.*?),',
		type => 'dissertation',
		subtype => 'monographical',
		institution => 'guess',
		faculty => '',
	},
	{
		pattern => 'Lic\.\sphil\.\sI,?\sUniv\.\sZ\x{fc}rich',
		type => 'masters_thesis',
		subtype => '',
		institution => 'University of Zurich',
		faculty => 'arts',
	},
	{
		pattern => 'Habilitationsschrift',
		type => 'habilitation',
		subtype => '',
		institution => '',
		faculty => '',
	},
	{
		pattern => 'Habil\.-Schr',
		type => 'habilitation',
		subtype => '',
		institution => '',
		faculty => '',
	},
];

#
# Mapping of 502_b / 900_a (degree type) to (thesis) type (check 502_b field map above)
# 
$c->{marcdegreetypemap} = {
	'Dissertation' => 'dissertation',
	'Diplomarbeit' => 'masters_thesis',
	'Habilitationsschrift' => 'habilitation',
	'Masterarbeit' => 'masters_thesis',
	'Lizenziatsarbeit' => 'masters_thesis',
	'Master-Arbeit' => 'masters_thesis',
};

#
# Mapping of 506_a (Terms governing access) to document security
#
$c->{marcaccessmap} = {
	'Closed Access' => 'staffonly',
	'Open Access' => 'public',
	'Restricted Access' => 'validuser',
	'Embargoed Access' => 'validuser',
};

#
# Mapping of 665_a (genre) to type
#
$c->{marcgenre2typemap} = {
	'Artikel' => 'article',
	'Aufgabensammlung' => 'monograph',
	'Buchkapitel' => 'book_section',
	'Electronic books.' => 'monograph',
	'Forschungsbericht' => 'published_research_report',
	'Herausgegebenes wissenschaftliches Werk' => 'edited_scientific_work',
	'Hochschulschrift' => 'dissertation',
	'Konferenzbeitrag' => 'conference_item',
	'Konferenzschrift' => 'conference_item',
	'Lehrbuch' => 'monograph',
	'Monografie' => 'monograph',
	'Textbooks' => 'monograph',
	'Wissenschaftliche Publikation in elektronischer Form (z.B. Datensatz)' => 'scientific_publication_in_electronic_form',
	'Working Paper' => 'working_paper',
	'Zeitungsartikel' => 'newspaper_article',
};

#
# Mapping of language codes MARC (Alma) -> EPrints
#
$c->{marclanguagemap} = {
	'aar' => 'aar', # Afar
	'abk' => 'abk', # Abkhaz
	'afr' => 'afr', # Afrikaans
	'aka' => 'aka', # Akan
	'ara' => 'ara', # Arabic
	'ave' => 'ave', # Avestan
	'bis' => 'bis', # Bislama
	'cat' => 'cat', # Catalan
	'czs' => 'ces', # Czech
	'wel' => 'cym', # Welsh
	'dan' => 'dan', # Danish
	'ger' => 'deu', # German
	'gre' => 'ell', # Greek, Modern 1821-
	'eng' => 'eng', # English
	'est' => 'est', # Estonian
	'per' => 'fas', # Persian, Modern
	'fin' => 'fin', # Finnish
	'fre' => 'fra', # French
	'ful' => 'ful', # Fulah
	'glg' => 'glg', # Galician
	'sla' => 'hbs', # Serbo-Croatian
	'heb' => 'heb', # Hebrew
	'hrv' => 'hrv', # Croatian
	'hun' => 'hun', # Hungarian
	'ind' => 'ind', # Indonesian
	'ice' => 'isl', # Icelandic
	'ita' => 'ita', # Italian
	'jpn' => 'jpn', # Japanese
	'geo' => 'kat', # Georgian
	'kir' => 'kir', # Kyrgyz
	'kor' => 'kor', # Korean
	'lat' => 'lat', # Latin
	'lav' => 'lav', # Latvian
	'lit' => 'lit', # Lithuanian
	'mac' => 'mkd', # Macedonian
	'nep' => 'nep', # Nepali
	'dut' => 'nld', # Dutch
	'nor' => 'nob', # Norwegian Bokmål
	'pol' => 'pol', # Polish
	'por' => 'por', # Portuguese
	'roh' => 'roh', # Romansh
	'rum' => 'ron', # Romanian, Moldovan
	'rus' => 'rus', # Russian
	'slo' => 'slk', # Slovak
	'slv' => 'slv', # Slovenian
	'spa' => 'spa', # Spanish; Castilian
	'alb' => 'sqi', # Albanian
	'srp' => 'srp', # Serbian
	'swe' => 'swe', # Swedish
	'syr' => 'syc', # Syriac
	'tur' => 'tur', # Turkish
	'ukr' => 'ukr', # Ukrainian
	'uzb' => 'uzb', # Uzbek
	'vie' => 'vie', # Vietnamese
	'chi' => 'zho', # Chinese
};

#
# Mapping of URLs to related URL type
#
$c->{url_856u_type_map} = {
	'deposit.d-nb.de' => 'catalog',
	'kth.diva-portal.org' => 'catalog',
	'toc.library.ethz.ch' => 'catalog',
	'urn.ub.unibe.ch' => 'catalog',
	'www.e-codices.unifr.ch' => 'catalog',
	'www.ub.unibas.ch' => 'catalog',
};

#
# Mapping of values of MARC field 900_b/909_b to faculty
#
$c->{facultymap} = {
	'01' => 'theology',
	'07' => 'science',
	'08' => 'arts',
	'09' => 'arts',
	'Abteilung für Schweinemedizin' => 'vetsuisse',
	'Abteilung für Veterinärepidemiologie' => 'vetsuisse',
	'Anthropologisches Institut' => 'science',
	'Center for Molecular Cardiology' => 'medicine',
	'Departement Kleintiere. Klinik für Kleintiermedizin, Abteilung Dermatologie' => 'vetsuisse',
	'Departement Pferde' => 'vetsuisse',
	'Departement Pferde. MSRU' => 'vetsuisse',
	'Departement der Nutztiere' => 'vetsuisse',
	'Departement der Nutztiere. Abteilung Schweinemedizin' => 'vetsuisse',
	'Departement für Diagnostik und klinische Services. Klinik für Bildgebende Diagnostik' => 'vetsuisse',
	'Departement für Kleintiere' => 'vetsuisse',
	'Departement für Kleintiere, Abteilung für Bildgebende Diagnostik und Radio-Onkologie' => 'vetsuisse',
	'Departement für Kleintiere, Klinik für Kleintierchirurgie' => 'vetsuisse',
	'Departement für Kleintiere, Klinik für Zoo-, Heim- und Wildtiere' => 'vetsuisse',
	'Departement für Kleintiere. Abteilung Radio-Onkologie' => 'vetsuisse',
	'Departement für Kleintiere. Abteilung für Bildgebende Diagnostik' => 'vetsuisse',
	'Departement für Kleintiere. Abteilung für Dermatologie' => 'vetsuisse',
	'Departement für Kleintiere. Abteilung für Radio-Onkologie' => 'vetsuisse',
	'Departement für Kleintiere. Klinik für Kleintierchirurgie' => 'vetsuisse',
	'Departement für Kleintiere. Klinik für Kleintiermedizin' => 'vetsuisse',
	'Departement für Kleintiere. Klinik für Kleintiermedizin. Abteilung Dermatologie' => 'vetsuisse',
	'Departement für Kleintiere. Klinik für Kleintiermedizin. Abteilung für Kardiologie' => 'vetsuisse',
	'Departement für Kleintiere. Klinik für Zoo-, Heim und Wildtiere' => 'vetsuisse',
	'Departement für Kleintiere. Klinik für Zoo-, Heim- und Wildtiere' => 'vetsuisse',
	'Departement für Klinische Diagnostik und Services. Klinik für bildgebende Diagnostik' => 'vetsuisse',
	'Departement für Klinische Diagnostik und Services. Veterinärmedizinisches Labor' => 'vetsuisse',
	'Departement für Nutztiere' => 'vetsuisse',
	'Departement für Nutztiere, Abteilung Schweinemedizin' => 'vetsuisse',
	'Departement für Nutztiere, Abteilung für Schweinemedizin' => 'vetsuisse',
	'Departement für Nutztiere, Klinik für Fortpflanzungsmedizin' => 'vetsuisse',
	'Departement für Nutztiere. Abteilung Ambulanz und Bestandesmedizin' => 'vetsuisse',
	'Departement für Nutztiere. Abteilung Andrologie und Assistierte Reproduktion' => 'vetsuisse',
	'Departement für Nutztiere. Abteilung für Ambulanz und Bestandesmedizin' => 'vetsuisse',
	'Departement für Nutztiere. Abteilung für Bildgebende Diagnostik' => 'vetsuisse',
	'Departement für Nutztiere, Abteilung für Schweinemedizin' => 'vetsuisse',
	'Departement für Nutztiere. Abteilung für Schweinemedizin' => 'vetsuisse',
	'Departement für Nutztiere. Abteilung für Wiederkäuerchirurgie' => 'vetsuisse',
	'Departement für Nutztiere. Klinik für Fortpflanzungsmedizin' => 'vetsuisse',
	'Departement für Nutztiere. Klinik für Reproduktionsmedizin' => 'vetsuisse',
	'Departement für Nutztiere. Klinik für Reproduktionsmedizin, Abteilung für Kleintierreproduktion' => 'vetsuisse',
	'Departement für Nutztiere. Klinik für Wiederkäuer' => 'vetsuisse',
	'Departement für Nutztiere. Veterinärmedizinisches Labor' => 'vetsuisse',
	'Departement für Nutztiere. Veterinärmediznisches Labor' => 'vetsuisse',
	'Departement für Nutztierklinik. Veterinärmedizinisches Labor' => 'vetsuisse',
	'Departement für Pferd' => 'vetsuisse',
	'Departement für Pferde' => 'vetsuisse',
	'Departement für Pferde, Klinik für Pferdechirurgie' => 'vetsuisse',
	'Departement für Pferde. Klinik für Pferdechirurgie' => 'vetsuisse',
	'Departement für Pferde, Musculoskeletal Research Unit' => 'vetsuisse',
	'Departement für Pferde. Abteilung Anästehsiologie' => 'vetsuisse',
	'Departement für Pferde. Abteilung Anästhesiologie' => 'vetsuisse',
	'Departement für Pferde. Abteilung für Anästhesiologie' => 'vetsuisse',
	'Departement für Pferde. Abteilung für Ophthalmologie' => 'vetsuisse',
	'Departement für Pferde. Abteilung für Sportmedizin Pferd' => 'vetsuisse',
	'Departement für Pferde. Klinik für Pferdechirurgie' => 'vetsuisse',
	'Departement für Pferde. Klinik für Pferdemedizin' => 'vetsuisse',
	'Departement für Pferde. Musculoskeletal Research Unit' => 'vetsuisse',
	'Departement für Pferde. Musculoskeletal Research Unit (MSRU)' => 'vetsuisse',
	'Departement für klinische Diagnostik und Services, Abteilung für Anästhesiologie' => 'vetsuisse',
	'Departement für klinische Diagnostik und Services. Abteilung Anästhesiologie' => 'vetsuisse',
	'Departement für klinische Diagnostik und Services. Abteilung für Anästhesiologie' => 'vetsuisse',
	'Departement für klinische Diagnostik und Services. Veterinärmedizinisches Labor' => 'vetsuisse',
	'Department für Kleintiere' => 'vetsuisse',
	'Department für Kleintiere, Klinik für Kleintiermedizin' => 'vetsuisse',
	'Department für Kleintiere. Klinik für Zoo-, Heim- und Wilditere' => 'vetsuisse',
	'Department für Kleintiere. Klinik für Zoo-, Heim- und Wildtiere' => 'vetsuisse',
	'Department für Nutztiere' => 'vetsuisse',
	'Department für Pferde. Abteilung für Anästhesiologie' => 'vetsuisse',
	'Department für Pferde. Klinik für Pferdechirurgie' => 'vetsuisse',
	'Department of Evolutionary Biology and Environmental Studies' => 'science',
	'Department of Informatics' => 'economics',
	'Derpartment of Informatics' => 'economics',
	'Deutsches Seminar' => 'arts',
	'ETH' => 'arts',  # due to original fulltext
	'Ethik-Zentrum der Universität Zürich. Institut für Biomedizinische Ethik' => 'medicine',
	'Facoltà di Lettere' => 'arts',
	'Faculdade de Filosofia e Letras' => 'arts',
	'Faculty of Arts' => 'arts',
	'Faculty of Arts and Social Science' => 'arts',
	'Faculty of Arts and Social Sciences' => 'arts',
	'Faculty of Business, Economics and Informatics' => 'economics',
	'Faculty of Economics, Business Administration and Information Technology' => 'economics',
	'Faculty of Economics, Business Administration and Information Technology ot the University of Zurich' => 'economics',
	'Faculty of Mathematics and Natural Sciences' => 'science',
	'Faculty of Medicine' => 'medicine',
	'Faculty of Science' => 'science',
	'Faculty of business, economics and informatics' => 'economics',
	'Faculté des lettres' => 'arts',
	'Geographisches Institut' => 'science',
	'Historisches Seminar' => 'arts',
	'Historisches Seminar. Abteilung Osteuropäische Geschichte' => 'arts',
	'Historisches Seminar. Forschungsstelle für Sozial- und Wirtschaftsgeschichte' => 'arts',
	'Institut für Bildgebende Diagnostik und Radio-Onkologie' => 'medicine',
	'Institut für Biomedizinische Ethik und Medizingeschichte' => 'medicine',
	'Institut für Epidemiologie, Biostatistik und Prävention' => 'medicine',
	'Institut für Epidemiologie, Biostatistik und Prävention. Zentrum für Reisemedizin' => 'medicine',
	'Institut für Evolutionsbiologie und Umweltwissenschaften' => 'science',
	'Institut für Hirnforschung' => 'medicine',
	'Institut für Informatik' => 'economics',
	'Institut für Labortierkunde' => 'vetsuisse',
	'Institut für Labortierkunded' => 'vetsuisse',
	'Institut für Lebensmittelsicherheit -und hygiene' => 'vetsuisse',
	'Institut für Lebensmittelsicherheit und -Hygiene' => 'vetsuisse',
	'Institut für Lebensmittelsicherheit und -hygiene' => 'vetsuisse',
	'Institut für Lebensmittelsicherheit und -hygiene. Abteilung für Geflügel- und Kaninchenkrankheiten' => 'vetsuisse',
	'Institut für Lebensmittelsicherheit und -hygiene. Abteilung für Veterinärbakteriologie' => 'vetsuisse',
	'Institut für Mathematik' => 'science',
	'Institut für Molekulare Mechanismen bei Krankheiten' => 'vetsuisse',
	'Institut für Parasitologie' => 'vetsuisse',
	'Institut für Politikwissenschaft' => 'arts',
	'Institut für Publizistikwissenschaft und Medienforschung' => 'arts',
	'Institut für Rechtsmedizin' => 'medicine',
	'Institut für Sonderpädagogik' => 'arts',
	'Institut für Systematische Botanik' => 'science',
	'Institut für Tierernährung' => 'vetsuisse',
	'Institut für Veteirnärbakteriologie' => 'vetsuisse',
	'Institut für Veterinäphysiologie' => 'vetsuisse',
	'Institut für Veterinärbakteriologie' => 'vetsuisse',
	'Institut für Veterinärbiochemie und Molekularbiologie' => 'vetsuisse',
	'Institut für Veterinärparasitologie' => 'vetsuisse',
	'Institut für Veterinärpathologie' => 'vetsuisse',
	'Institut für Veterinärpharmakologie und -toxikologie' => 'vetsuisse',
	'Institut für Veterinärphysiologie' => 'vetsuisse',
	'Institute of Biomedical Ethics and History of Medicine' =>  'medicine',
	'Institute of Veterinary Biochemistry and Molecular Biology' => 'vetsuisse',
	'Kantonsspital Baden AG. Institut für Radiologie' => 'medicine',
	'Kantonsspital Baden. Klinik für Innere Medizin' => 'medicine',
	'Kantonsspital St. Gallen. Experimentelle Dermatologie am Institut für Immunbiologie' => 'medicine',
	'Kantonsspital St. Gallen. Klinik für Allgemein-, Viszeral-, Endokrin- und Transplantationschirurgie' => 'medicine',
	'Kantonsspital St. Gallen. Klinik für Gastroenterologie und Hepatologie' => 'medicine',
	'Kantonsspital St. Gallen. Klinik für Urologie' => 'medicine',
	'Kantonsspital Winterthur. Departement Chirurgie. Klinik für Urologie' => 'medicine',
	'Kantonsspital Winterthur. Klinik für Urologie' => 'medicine',
	'Kinderspital Zürich. Abteilung Anästhesie' => 'medicine',
	'Kinderspital Zürich. Abteilung Entwicklungspädiatrie' => 'medicine',
	'Kinderspital Zürich. Abteilung für Stoffwechselkrankheiten' => 'medicine',
	'Kinderspital Zürich. Kardiologie'  => 'medicine',
	'Kinderspital Zürich. Rehabilitationszentrum Affoltern am Albis' => 'medicine',
	'Klinik der Kleintiermedizin' => 'vetsuisse',
	'Klinik für Fortpflanzungsmedizin' => 'vetsuisse',
	'Klinik für Kleintierchirurgie' => 'vetsuisse',
	'Klinik für Kleintiermedizin' => 'vetsuisse',
	'Klinik für Kleintiermedizin, Abteilung für Kardiologie' => 'vetsuisse',
	'Klinik für Kleintiermedizin. Abteilung für Kardiologie' => 'vetsuisse',
	'Klinik für Neuroradiologie' => 'medicine',
	'Klinik für Pferdemedizin' => 'vetsuisse',
	'Klinik für Reproduktionsmedizin' => 'vetsuisse',
	'Klinik für Reproduktionsmedizin. Abteilung für Grosstierreproduktion' => 'vetsuisse',
	'Klinik für Reproduktionsmedizin. Abteilung für Kleintierreproduktion' => 'vetsuisse',
	'Klinik für Zoo-, Heim- und Wildtiere' => 'vetsuisse',
	'Luzerner Kantonsspital. Augenklinik'  => 'medicine',
	'Luzerner Kantonsspital. Kinderspital Luzern' => 'medicine',
	'Mathematisch-Naturwissenschaftliche Fakultät' => 'science',
	'Mathematisch-naturwissenschaftiche Fakultät' => 'science',
	'Mathematisch-naturwissenschaftliche Fakultät' => 'science',
	'Mathematisch-naturwissenschaftliche Fakultät der Universität Zürich' => 'science',
	'Mathematisch-naturwissenschaftlichen Fakultät' => 'science',
	'Mathematisch-naturwissenschftliche Fakultät' => 'science',
	'Mathematisches-Institut' => 'science',
	'Medizinische Fakultät' => 'medicine',
	'Musculoskeletal Research Unit (MSRU)' => 'vetsuisse',
	'Organisch-Chemisches Institut' => 'science',
	'Ostasiatisches Seminar der Universität Zürich' => 'arts',
	'Ostschweizer Kinderspital. Pädiatrie' => 'medicine',
	'Paläontologisches Institut und Museum' => 'science',
	'Pferdeklink' => 'vetsuisse',
	'Philosophische Fakultät' => 'arts',
	'Physiologisches Institut' => 'medicine',
	'Psychiatrische Universitätsklinik Zürich (PUK)' => 'medicine',
	'Psychiatrische Universitätsklinik Zürich. Klinik für Psychiatrie, Psychotherapie und Psychosomatik' => 'medicine',
	'Psychiatrische Universitätsklinik Zürich. Lehrstuhl für Psychiatrie' => 'medicine',
	'Psychiatrische Universitätsklinik. Klinik für Psychiatrie, Psychotherapie und Psychosomatik KPPP' => 'medicine',
	'Psychologisches Institut' => 'arts',
	'Pädagogisches Institut' => 'arts',
	'Rechtswissenschaftliche Fakultät' => 'law',
	'Rechtswissenschaftliche Fakultät der Universität Zürich' => 'law',
	'Soziologisches Institut' => 'arts',
	'Stadtspital Triemli Zürich. Institut für Anästhesiologie und Intensivmedizin' => 'medicine',
	'Stadtspital Triemli. Augenklinik' => 'medicine',
	'Stadtspital Triemli. Klinik für Herzchirurgie' => 'medicine',
	'Stadtspital Waid Zürich. Departement Chirurgie' => 'medicine',
	'Theologische Fakultät' => 'theology',
	'University of Zurich. Institute of Biomedical Ethics and History of Medicine' => 'medicine',
	'University Hospital Zurich. Department of Surgery and Transplantation' => 'medicine',
	'University Hospital Zurich. Division of Nephrology' => 'medicine',
	'Universität Zürich - Campus Schlieren. Institut für regenerative Medizin' => 'medicine',
	'Universität Zürich. Institut für Biomedizinische Ethik und Medizingeschichte' => 'medicine',
	'Universität Zürich. Institut für Epidemiologie, Biostatistik und Prävention' => 'medicine',
	'Universität Zürich. Institut für Evolutionäre Medizin' => 'medicine',
	'Universität Zürich. Institut für Rechtsmedizin' => 'medicine',
	'Universität Zürich. Physiologisches Institut' => 'medicine',
	'Universität Zürich. Zentrum für Zahnmedizin. Klinik für Kaufunktionstörungen (KFS)' => 'medicine',
	'Universität Zürich. Zentrum für Zahnmedizin. Klinik für Kieferorthopädie und Kinderzahnmedizin' => 'medicine',
	'Universität Zürich. Zentrum für Zahnmedizin. Klinik für Kronen- und Brückenprothetik, Teilprothetik und zahnärztliche Materialkunde' => 'medicine',
	'Universität Zürich. Zentrum für Zahnmedizin. Klinik für Präventivzahnmedizin, Parodontologie und Kariologie' => 'medicine',
	'Universität Zürich. Zentrum für Zahnmedizin. Klinik für Präventivzahnmedizin, Parodontologie und Kariologie (PPK)' => 'medicine',
	'Universitäts-Kinderspital' => 'medicine',
	'Universitäts-Kinderspital Zürich' => 'medicine',
	'Universitäts-Kinderspital Zürich - Eleonorenstiftung. Abteilung Psychosomatik und Psychiatrie' => 'medicine',
	'Universitäts-Kinderspital Zürich- Eleonorenstiftung. Abteilung Pädiatrische Kardiologie' => 'medicine',
	'Universitäts-Kinderspital Zürich. Anästhesie' => 'medicine',
	'Universitäts-Kinderspital Zürich. Anästhesieabteilung' => 'medicine',
	'Universitäts-Kinderspital Zürich. Chirurgische Klinik' => 'medicine',
	'Universitäts-Kinderspital Zürich. Das Spital der Eleonorenstiftung' => 'medicine',
	'Universitäts-Kinderspital Zürich. Pädiatrische Kardiologie' => 'medicine',
	'Universitäts-Kinderspital. Abteilung für Stoffwechselkrankheiten' => 'medicine',
	'UniversitätsKinderspital. Medizinische Klinik. Abteilung Onkologie' => 'medicine',	
	'UniversitätsSpital Zürich. Institut für Anästhesiologie' => 'medicine',	 
	'UniversitätsSpital Zürich. Institut für komplementäre und integrative Medizin' => 'medicine',
	'UniversitätsSpital Zürich. Klinik für Geriatrie' => 'medicine',
	'UniversitätsSpital Zürich. Klinik für Kardiologie' => 'medicine', 
	'UniversitätsSpital Zürich. Klinik für Nuklearmedizin' => 'medicine',
	'UniversitätsSpital Zürich. Klinik für Traumatologie' => 'medicine',
	'UniversitätsSpital Zürich. Klinik für klinische Pharmakologie und Toxikologie' => 'medicine',
	'UniversitätsSpital Zürich. Universitäres Herzzentrum' => 'medicine',
	'UniversitätsSpital Zürich. Universitäres Herzzentrum, Klinik für Kardiologie' => 'medicine',
	'UniversitätsSpital. Augenklinik' => 'medicine', 
	'UniversitätsSpital. Klinik für Dermatologie' => 'medicine', 
	'UniversitätsSpital. Klinik für Geburtshilfe' => 'medicine',
	'UniversitätsSpital. Klinik für Neonatologie' => 'medicine',
	'UniversitätsSpital. Klinik für Neurochirurgie' => 'medicine', 
	'UniversitätsSpital. Klinik für Neurologie' => 'medicine', 
	'UniversitätsSpital. Klinik für Plastische Chirurgie und Handchirurgie' => 'medicine', 
	'Universitätsklinik Balgrist' => 'medicine', 
	'Universitätsklinik Balgrist, Zürich. Abteilung für Anästhesiologie, Intensivmedizin und Schmerztherapie' => 'medicine',
	'Universitätsklinik Balgrist Zürich. Chiropraktische Medizin' => 'medicine', 
	'Universitätsklinik Balgrist. Abteilung für Anästhesiologie' => 'medicine',
	'Universitätsklinik Balgrist. Abteilung für Orthopädie' => 'medicine',
	'Universitätsklinik Balgrist. Klinik für Orthopädie' => 'medicine',
	'Universitätsklinik Balgrist. Labor für Orthopädische Biomechanik' => 'medicine',
	'Universitätsklinik Balgrist. Orthopädie' => 'medicine',
	'Universitätsklinik Balgrist. Orthopädische Klinik' => 'medicine',
	'Universitätsklinik Balgrist. Zentrum für Paraplegie' => 'medicine',
	'Universitätspital Zürich. Klinik für Infektionskrankheiten und Spitalhygiene' => 'medicine',
	'Universitätssital Zürich. Klinik für Kardiologie' => 'medicine',
	'Universitätsspital Balgrist. Klinik für Orthopädie' => 'medicine',
	'Universitätsspital Zürich. Abteilung für Kardiologie' => 'medicine',
	'Universitätsspital Zürich. Augenklinik' => 'medicine',
	'Universitätsspital Zürich. Departement Chirurgie. Klinik für Unfallchirurgie' => 'medicine',
	'Universitätsspital Zürich. Departement Medizinische Radiologie. Klinik und Poliklinik für Nuklearmedizin' => 'medicine',
	'Universitätsspital Zürich. Dermatologische Klinik' => 'medicine',
	'Universitätsspital Zürich. Institut für Anästhesiologie' => 'medicine',
	'Universitätsspital Zürich. Institut für Diagnostische und Interventionelle Radiologie' => 'medicine',
	'Universitätsspital Zürich. Institut für Hausarztmedizin' => 'medicine',
	'Universitätsspital Zürich. Institut für Intensivmedizin' => 'medicine',
	'Universitätsspital Zürich. Institut für Klinische Chemie' => 'medicine',
	'Universitätsspital Zürich. Institut für Medizinische Mikrobiologie' => 'medicine',
	'Universitätsspital Zürich. Institut für Pathologie und Molekularpathologie' => 'medicine',
	'Universitätsspital Zürich. Institut für diagnostische und interventionelle Radiologie' => 'medicine',
	'Universitätsspital Zürich. Institut für klinische Chemie und Klinik für Urologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Angiologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Augenheilkunde' => 'medicine',
	'Universitätsspital Zürich. Klinik für Endokrinologie, Diabetologie und klinische Ernährung' => 'medicine',
	'Universitätsspital Zürich. Klinik für Gastroenterologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Gastroenterologie und Hepatologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Geburtshilfe' => 'medicine',
	'Universitätsspital Zürich. Klinik für Geriatrie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Gynäkologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Hämatologie. Bereich III, Departement für Innere Medizin' => 'medicine',
	'Universitätsspital Zürich. Klinik für Immunologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Infektionskranheiten und Spitalhygiene' => 'medicine',
	'Universitätsspital Zürich. Klinik für Infektionskrankheiten und Spitalhygiene' => 'medicine',
	'Universitätsspital Zürich. Klinik für Kardiologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Kardiologie, Rhythmologie/Devices' => 'medicine',
	'Universitätsspital Zürich. Klinik für Klinische Pharmakologie und Toxikologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Konsiliarpsychiatrie und Psychosomatik' => 'medicine',
	'Universitätsspital Zürich. Klinik für Medizinische Onkologie und Hämatologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Mund-, Kiefer- und Gesichtschirurgie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Neonatologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Nephrologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Neurochirurgie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Neurologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Nuklearmedizin' => 'medicine',
	'Universitätsspital Zürich. Klinik für Ohren-, Nasen-, Hals- und Gesichtschirurgie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Otorhinolaryngologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Plastische Chirurgie und Handchirurgie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Pneumologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Psychiatrie und Psychotherapie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Radio-Onkologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Reproduktions-Endokrinologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Rheumatologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Thoraxchirurgie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Traumatologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Unfallchirurgie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Urologie' => 'medicine',
	'Universitätsspital Zürich. Klinik für Viszeral- und Transplantationschirurgie' => 'medicine',
	'Universitätsspital Zürich. Klinik und Poliklinik für Innere Medizin' => 'medicine',
	'Universitätsspital Zürich. Klinik und Poliklinik für Nuklearmedizin' => 'medicine',
	'Universitätsspital Zürich. Klinik und Polyklinik für Innere Medizin' => 'medicine',
	'Universitätsspital Zürich. Universitäres Herzzentrum' => 'medicine',
	'Universitätsspital Zürich. Universitäres Herzzentrum Zürich. Klinik für Kardiologie' => 'medicine',
	'Universitätsspital Zürich. Zentrum für Hämatologie und Onkologie' => 'medicine',
	'Universitätsspital. Klinik für Traumatologie' => 'medicine',
	'Unversitätsklinik Balgrist. Klinik für Orthopädie' => 'medicine',		
	'Veterinär-Anatomisches Institut' => 'vetsuisse',
	'Veterinär-anatomisches Institut' => 'vetsuisse',
	'Veterinäranatomisches Institut' => 'vetsuisse',
	'Veterinärmdizinische Genetik' => 'vetsuisse',
	'Veterinärmedizinische Fakultät' => 'vetsuisse',
	'Veterinärmedizinisches Labor' => 'vetsuisse',
	'Vetsuisse-Fakultät' => 'vetsuisse',
	'Vetsuisse-Fakultät Zürich' => 'vetsuisse',
	'Vetsuisse-Fakultät. Institut für Tierernährung' => 'vetsuisse',
	'Virologisches Institut' => 'vetsuisse',
	'Völkerkundemuseum Zürich' => 'arts',
	'Wirtschaftswissenschaftliche Fakultät' => 'economics',
	'Wirtschaftswissenschaftliche Fakultät der Universität Zürich' => 'economics',
	'Zentrum für Zahn-, Mund- und Kieferheilkunde. Klinik für Präventivzahnmedizin, Parodontologie und Kariologie' => 'medicine',
	'Zentrum für Zahnmedizin Klinik für Präventivzahnmedizin, Parodontologie und Kariologie'  => 'medicine',
	'Zentrum für Zahnmedizin. Klinik für Kieferorthopädie und Kinderzahnmedizin' => 'medicine',
	'Zentrum für Zahnmedizin. Klinik für Kronen- und Brückenprothetik, Teilprothetik und zahnärztliche Materialkunde' => 'medicine',
	'Zentrum für Zahnmedizin. Klinik für Mund-, Kiefer- und Gesichtschirurgie' => 'medicine',
	'Zentrum für Zahnmedizin. Klinik für Mund-, Kiefer- und Gesichtschirurgie - Klinik für Oralchirurgie' => 'medicine',
	'Zentrum für Zahnmedizin. Klinik für Präventivzahnmedizin, Parodontologie und Kariologie' => 'medicine',
	'Zentrum für Zahnmedizin. Klinik für Präventivzahnmedizin, Parodontologie und Kariologie (PPK)' => 'medicine',
};

#
# Mapping of values of MARC field 909_b to collection(s)
#
$c->{collectionsmap} = {
	'Abteilung für Schweinemedizin' => [ '10187' ],
	'Abteilung für Veterinärepidemiologie' => [ '10599' ],
	'Anthropologisches Institut' => [ '10207' ],
	'Center for Molecular Cardiology' => [ '11459' ],
	'Departement Kleintiere. Klinik für Kleintiermedizin, Abteilung Dermatologie' => [ '10253' ],
	'Departement Pferde' => [ '10090' ],
	'Departement Pferde. MSRU' => [ '10090' ],
	'Departement der Nutztiere' => [ '10187' ],
	'Departement der Nutztiere. Abteilung Schweinemedizin' => [ '10187' ],
	'Departement für Diagnostik und klinische Services. Klinik für Bildgebende Diagnostik' => [ '11404' ],
	'Departement für Kleintiere' => [ '10253' ],
	'Departement für Kleintiere, Abteilung für Bildgebende Diagnostik und Radio-Onkologie' => [ '10253', '11404' ],
	'Departement für Kleintiere, Klinik für Kleintierchirurgie' => [ '10253' ],
	'Departement für Kleintiere, Klinik für Zoo-, Heim- und Wildtiere' => [ '10253' ],
	'Departement für Kleintiere. Abteilung Radio-Onkologie' => [ '10253', '11404' ],
	'Departement für Kleintiere. Abteilung für Bildgebende Diagnostik' => [ '10253', '11404' ],
	'Departement für Kleintiere. Abteilung für Dermatologie' => [ '10253' ],
	'Departement für Kleintiere. Abteilung für Radio-Onkologie' => [ '10253', '11404' ],
	'Departement für Kleintiere. Klinik für Kleintierchirurgie' => [ '10253' ],
	'Departement für Kleintiere. Klinik für Kleintiermedizin' => [ '10253' ],
	'Departement für Kleintiere. Klinik für Kleintiermedizin. Abteilung Dermatologie' => [ '10253' ],
	'Departement für Kleintiere. Klinik für Kleintiermedizin. Abteilung für Kardiologie' => [ '10253' ],
	'Departement für Kleintiere. Klinik für Zoo-, Heim und Wildtiere' => [ '10253' ],
	'Departement für Kleintiere. Klinik für Zoo-, Heim- und Wildtiere' => [ '10253' ],
	'Departement für Klinische Diagnostik und Services. Klinik für bildgebende Diagnostik' => [ '11404' ],
	'Departement für Klinische Diagnostik und Services. Veterinärmedizinisches Labor' => [ '11404' ],
	'Departement für Nutztiere' => [ '10187' ],
	'Departement für Nutztiere, Abteilung Schweinemedizin' => [ '10187' ],
	'Departement für Nutztiere, Abteilung für Schweinemedizin' => [ '10187' ],
	'Departement für Nutztiere, Abteilung für Schweinemedizin' => [ '10187' ],
	'Departement für Nutztiere, Klinik für Fortpflanzungsmedizin' => [ '10187' ],
	'Departement für Nutztiere. Abteilung Ambulanz und Bestandesmedizin' => [ '10187' ],
	'Departement für Nutztiere. Abteilung Andrologie und Assistierte Reproduktion' => [ '10187' ],
	'Departement für Nutztiere. Abteilung für Ambulanz und Bestandesmedizin' => [ '10187' ],
	'Departement für Nutztiere. Abteilung für Bildgebende Diagnostik' => [ '10187', '11404' ],
	'Departement für Nutztiere. Abteilung für Schweinemedizin' => [ '10187' ],
	'Departement für Nutztiere. Abteilung für Wiederkäuerchirurgie' => [ '10187' ],
	'Departement für Nutztiere. Klinik für Fortpflanzungsmedizin' => [ '10187' ],
	'Departement für Nutztiere. Klinik für Reproduktionsmedizin' => [ '10187' ],
	'Departement für Nutztiere. Klinik für Reproduktionsmedizin, Abteilung für Kleintierreproduktion' => [ '10187' ],
	'Departement für Nutztiere. Klinik für Wiederkäuer' => [ '10187' ],
	'Departement für Nutztiere. Veterinärmedizinisches Labor' => [ '10187' ],
	'Departement für Nutztiere. Veterinärmediznisches Labor' => [ '10187' ],
	'Departement für Nutztierklinik. Veterinärmedizinisches Labor' => [ '10187' ],
	'Departement für Pferd' => [ '10090' ],
	'Departement für Pferde' => [ '10090' ],
	'Departement für Pferde, Klinik für Pferdechirurgie' => [ '10090' ],
	'Departement für Pferde. Klinik für Pferdechirurgie' => [ '10090' ],
	'Departement für Pferde, Musculoskeletal Research Unit' => [ '10090' ],
	'Departement für Pferde. Abteilung Anästehsiologie' => [ '10090' ],
	'Departement für Pferde. Abteilung Anästhesiologie' => [ '10090' ],
	'Departement für Pferde. Abteilung für Anästhesiologie' => [ '10090' ],
	'Departement für Pferde. Abteilung für Ophthalmologie' => [ '10090' ],
	'Departement für Pferde. Abteilung für Sportmedizin Pferd' => [ '10090' ],
	'Departement für Pferde. Klinik für Pferdechirurgie' => [ '10090' ],
	'Departement für Pferde. Klinik für Pferdemedizin' => [ '10090' ],
	'Departement für Pferde. Musculoskeletal Research Unit' => [ '10090' ],
	'Departement für Pferde. Musculoskeletal Research Unit (MSRU)' => [ '10090' ],
	'Departement für klinische Diagnostik und Services, Abteilung für Anästhesiologie' => [ '11404' ],
	'Departement für klinische Diagnostik und Services. Abteilung Anästhesiologie' => [ '11404' ],
	'Departement für klinische Diagnostik und Services. Abteilung für Anästhesiologie' => [ '11404' ],
	'Departement für klinische Diagnostik und Services. Veterinärmedizinisches Labor' => [ '11404' ],
	'Department für Kleintiere' => [ '10253' ],
	'Department für Kleintiere, Klinik für Kleintiermedizin' => [ '10253' ],
	'Department für Kleintiere. Klinik für Zoo-, Heim- und Wilditere' => [ '10253' ],
	'Department für Kleintiere. Klinik für Zoo-, Heim- und Wildtiere' => [ '10253' ],
	'Department für Nutztiere' => [ '10187' ],
	'Department für Pferde. Abteilung für Anästhesiologie' => [ '10090' ],
	'Department für Pferde. Klinik für Pferdechirurgie' => [ '10090' ],
	'Department of Evolutionary Biology and Environmental Studies' => [ '10127' ],
	'Department of Informatics' => [ '10009' ],
	'Derpartment of Informatics' => [ '10009' ],
	'Deutsches Seminar' => [ '10096' ],
	'Ethik-Zentrum der Universität Zürich. Institut für Biomedizinische Ethik' => [ '10222'],
	'Geographisches Institut' => [ '10122' ],
	'Historisches Seminar' => [ '10109' ],
	'Historisches Seminar. Abteilung Osteuropäische Geschichte' => [ '10109' ],
	'Historisches Seminar. Forschungsstelle für Sozial- und Wirtschaftsgeschichte' => [ '10109' ],
	'Institut für Bildgebende Diagnostik und Radio-Onkologie' => [ '11404' ],
	'Institut für Biomedizinische Ethik und Medizingeschichte' => [ '10222' ],
	'Institut für Epidemiologie, Biostatistik und Prävention' => [ '10060' ],
	'Institut für Epidemiologie, Biostatistik und Prävention. Zentrum für Reisemedizin' => [ '10060' ],
	'Institut für Evolutionsbiologie und Umweltwissenschaften' => [ '10127' ],
	'Institut für Hirnforschung' => [ '10242' ],
	'Institut für Informatik' => [ '10009' ],
	'Institut für Labortierkunde' => [ '10239' ],
	'Institut für Labortierkunded' => [ '10239' ],
	'Institut für Lebensmittelsicherheit -und hygiene' => [ '10082' ],
	'Institut für Lebensmittelsicherheit und -Hygiene' => [ '10082' ],
	'Institut für Lebensmittelsicherheit und -hygiene' => [ '10082' ],
	'Institut für Lebensmittelsicherheit und -hygiene. Abteilung für Geflügel- und Kaninchenkrankheiten' => [ '10082' ],
	'Institut für Lebensmittelsicherheit und -hygiene. Abteilung für Veterinärbakteriologie' => [ '10082' ],
	'Institut für Mathematik' => [ '10123' ],
	'Institut für Molekulare Mechanismen bei Krankheiten' => [ '10226' ],
	'Institut für Parasitologie' => [ '10078' ],
	'Institut für Politikwissenschaft' => [ '10113' ],
	'Institut für Publizistikwissenschaft und Medienforschung' => [ '10240' ],
	'Institut für Rechtsmedizin' => [ '10218' ],
	'Institut für Systematische Botanik' => [ '10121' ],
	'Institut für Tierernährung' => [ '10227' ],
	'Institut für Veteirnärbakteriologie' => [ '10185' ],
	'Institut für Veterinäphysiologie' => [ '10081' ],
	'Institut für Veterinärbakteriologie' => [ '10185' ],
	'Institut für Veterinärbiochemie und Molekularbiologie' => [ '10226' ],
	'Institut für Veterinärparasitologie' => [ '10078' ],
	'Institut für Veterinärpathologie' => [ '10184' ],
	'Institut für Veterinärpharmakologie und -toxikologie' => [ '10079' ],
	'Institut für Veterinärphysiologie' => [ '10081' ],
	'Institute of Biomedical Ethics and History of Medicine' => [ '10222' ],
	'Institute of Veterinary Biochemistry and Molecular Biology' => [ '10226' ],
	'Kinderspital Zürich. Abteilung Anästhesie' => [ '10220' ],
	'Kinderspital Zürich. Abteilung Entwicklungspädiatrie' => [ '10036' ],
	'Kinderspital Zürich. Abteilung für Stoffwechselkrankheiten' => [ '10036' ],
	'Kinderspital Zürich. Kardiologie' => [ '10036' ],
	'Kinderspital Zürich. Rehabilitationszentrum Affoltern am Albis' => [ '10036' ],
	'Klinik der Kleintiermedizin' => [ '10253' ],
	'Klinik für Fortpflanzungsmedizin' => [ '10187' ],
	'Klinik für Kleintierchirurgie' => [ '10253' ],
	'Klinik für Kleintiermedizin' => [ '10253' ],
	'Klinik für Kleintiermedizin, Abteilung für Kardiologie' => [ '10253' ],
	'Klinik für Kleintiermedizin. Abteilung für Kardiologie' => [ '10253' ],
	'Klinik für Neuroradiologie' => [ '10043' ],
	'Klinik für Pferdemedizin' => [ '10090' ],
	'Klinik für Reproduktionsmedizin' => [ '10187' ],
	'Klinik für Reproduktionsmedizin. Abteilung für Grosstierreproduktion' => [ '10187' ],
	'Klinik für Reproduktionsmedizin. Abteilung für Kleintierreproduktion' => [ '10187' ],
	'Klinik für Zoo-, Heim- und Wildtiere' => [ '10253' ],
	'Mathematisches-Institut' => [ '10123' ],
	'Musculoskeletal Research Unit (MSRU)' => [ '10090' ],
	'Organisch-Chemisches Institut' => [ '10120' ],
	'Ostasiatisches Seminar der Universität Zürich' => [ '10106' ],
	'Paläontologisches Institut und Museum' => [ '10125' ],
	'Pferdeklink' => [ '10090' ],
	'Physiologisches Institut' => [ '10052' ],
	'Psychiatrische Universitätsklinik Zürich (PUK)' => [ '10054' ],
	'Psychiatrische Universitätsklinik Zürich. Klinik für Psychiatrie, Psychotherapie und Psychosomatik' => [ '10054' ],
	'Psychiatrische Universitätsklinik Zürich. Lehrstuhl für Psychiatrie' => [ '10054' ],
	'Psychiatrische Universitätsklinik. Klinik für Psychiatrie, Psychotherapie und Psychosomatik KPPP' => [ '10054' ],
	'Psychologisches Institut' => [ '10093' ],
	'Pädagogisches Institut' => [ '10091' ],
	'Soziologisches Institut' => [ '10095' ],
	'University Hospital Zurich. Department of Surgery and Transplantation' => [ '10022', '10217' ],
	'University Hospital Zurich. Division of Nephrology' => [ '10035' ],
	'University of Zurich. Institute of Biomedical Ethics and History of Medicine' => [ '10222' ],
	'Universität Zürich - Campus Schlieren. Institut für regenerative Medizin' => [ '11359' ],
	'Universität Zürich. Institut für Biomedizinische Ethik und Medizingeschichte' => [ '10222' ],
	'Universität Zürich. Institut für Epidemiologie, Biostatistik und Prävention' => [ '10060' ],
	'Universität Zürich. Institut für Evolutionäre Medizin' => [ '11294' ],
	'Universität Zürich. Institut für Rechtsmedizin' => [ '10218' ],
	'Universität Zürich. Physiologisches Institut' => [ '10052' ],
	'Universität Zürich. Zentrum für Zahnmedizin. Klinik für Kaufunktionstörungen (KFS)' => [ '10223' ],
	'Universität Zürich. Zentrum für Zahnmedizin. Klinik für Kieferorthopädie und Kinderzahnmedizin' => [ '10067' ],
	'Universität Zürich. Zentrum für Zahnmedizin. Klinik für Kronen- und Brückenprothetik, Teilprothetik und zahnärztliche Materialkunde' => [ '10068' ],
	'Universität Zürich. Zentrum für Zahnmedizin. Klinik für Präventivzahnmedizin, Parodontologie und Kariologie' => [ '10066' ],
	'Universität Zürich. Zentrum für Zahnmedizin. Klinik für Präventivzahnmedizin, Parodontologie und Kariologie (PPK)' => [ '10066' ],
	'Universitäts-Kinderspital Zürich - Eleonorenstiftung. Abteilung Psychosomatik und Psychiatrie'  => [ '10036' ],
	'Universitäts-Kinderspital Zürich- Eleonorenstiftung. Abteilung Pädiatrische Kardiologie'  => [ '10036' ],
	'Universitäts-Kinderspital Zürich. Anästhesie' => [ '10220' ],
	'Universitäts-Kinderspital Zürich. Anästhesieabteilung' => [ '10220' ],
	'Universitäts-Kinderspital Zürich. Chirurgische Klinik' => [ '10220' ],
	'Universitäts-Kinderspital Zürich. Das Spital der Eleonorenstiftung' => [ '10036' ],
	'Universitäts-Kinderspital Zürich. Pädiatrische Kardiologie' => [ '10036' ],
	'Universitäts-Kinderspital. Abteilung für Stoffwechselkrankheiten' => [ '10036' ],
	'UniversitätsKinderspital. Medizinische Klinik. Abteilung Onkologie'  => [ '10036' ],
	'UniversitätsSpital Zürich. Institut für Anästhesiologie' => [ '10216' ],
	'UniversitätsSpital Zürich. Institut für komplementäre und integrative Medizin' => [ '10034' ],
	'UniversitätsSpital Zürich. Klinik für Geriatrie' => [ '11221' ], 
	'UniversitätsSpital Zürich. Klinik für Kardiologie' => [ '10209' ], 
	'UniversitätsSpital Zürich. Klinik für Nuklearmedizin' => [ '10181' ],
	'UniversitätsSpital Zürich. Klinik für Traumatologie' => [ '10021' ],
	'UniversitätsSpital Zürich. Klinik für klinische Pharmakologie und Toxikologie' => [ '10199' ],
	'UniversitätsSpital Zürich. Universitäres Herzzentrum' => [ '10209' ],
	'UniversitätsSpital Zürich. Universitäres Herzzentrum, Klinik für Kardiologie' => [ '10209' ],
	'UniversitätsSpital. Augenklinik' => [ '10018' ], 
	'UniversitätsSpital. Klinik für Dermatologie' => [ '10177' ],
	'UniversitätsSpital. Klinik für Geburtshilfe' => [ '10026' ],
	'UniversitätsSpital. Klinik für Neonatologie' => [ '10027' ],
	'UniversitätsSpital. Klinik für Neurochirurgie' => [ '10180' ],
	'UniversitätsSpital. Klinik für Neurologie' => [ '10040' ],
	'UniversitätsSpital. Klinik für Plastische Chirurgie und Handchirurgie' => [ '10266' ],
	'Universitätsklinik Balgrist' => [ '10046' ],
	'Universitätsklinik Balgrist, Zürich. Abteilung für Anästhesiologie, Intensivmedizin und Schmerztherapie' => [ '10046' ],
	'Universitätsklinik Balgrist Zürich. Chiropraktische Medizin' => [ '10046' ],
	'Universitätsklinik Balgrist. Abteilung für Anästhesiologie' => [ '10046' ],
	'Universitätsklinik Balgrist. Abteilung für Orthopädie' => [ '10046' ],
	'Universitätsklinik Balgrist. Klinik für Orthopädie' => [ '10046' ],
	'Universitätsklinik Balgrist. Labor für Orthopädische Biomechanik' => [ '10046' ],
	'Universitätsklinik Balgrist. Orthopädie' => [ '10046' ],
	'Universitätsklinik Balgrist. Orthopädische Klinik' => [ '10046' ],
	'Universitätsklinik Balgrist. Zentrum für Paraplegie' => [ '10046' ],
	'Universitätspital Zürich. Klinik für Infektionskrankheiten und Spitalhygiene' => [ '10234' ],
	'Universitätssital Zürich. Klinik für Kardiologie' => [ '10209' ],
	'Universitätsspital Balgrist. Klinik für Orthopädie' => [ '10046' ],
	'Universitätsspital Zürich. Abteilung für Kardiologie' => [ '10209' ],
	'Universitätsspital Zürich. Augenklinik' => [ '10018' ],
	'Universitätsspital Zürich. Departement Chirurgie. Klinik für Unfallchirurgie' => [ '10021' ],
	'Universitätsspital Zürich. Departement Medizinische Radiologie. Klinik und Poliklinik für Nuklearmedizin' => [ '10181' ],
	'Universitätsspital Zürich. Dermatologische Klinik' => [ '10177' ],
	'Universitätsspital Zürich. Institut für Anästhesiologie' => [ '10216' ],
	'Universitätsspital Zürich. Institut für Diagnostische und Interventionelle Radiologie' => [ '10042' ],
	'Universitätsspital Zürich. Institut für Hausarztmedizin' => [ '11035' ],
	'Universitätsspital Zürich. Institut für Intensivmedizin' => [ '10023' ],
	'Universitätsspital Zürich. Institut für Klinische Chemie' => [ '10038' ],
	'Universitätsspital Zürich. Institut für Medizinische Mikrobiologie' => [ '10179' ],
	'Universitätsspital Zürich. Institut für Pathologie und Molekularpathologie' => [ '10049' ],
	'Universitätsspital Zürich. Institut für diagnostische und interventionelle Radiologie' => [ '10042' ],
	'Universitätsspital Zürich. Institut für klinische Chemie und Klinik für Urologie' => [ '10038', '10062' ],
	'Universitätsspital Zürich. Klinik für Angiologie' => [ '10031' ],
	'Universitätsspital Zürich. Klinik für Augenheilkunde' => [ '10018' ],
	'Universitätsspital Zürich. Klinik für Endokrinologie, Diabetologie und klinische Ernährung' => [ '10265' ],
	'Universitätsspital Zürich. Klinik für Gastroenterologie' => [ '10219' ],
	'Universitätsspital Zürich. Klinik für Gastroenterologie und Hepatologie' => [ '10219' ],
	'Universitätsspital Zürich. Klinik für Geburtshilfe' => [ '10026' ],
	'Universitätsspital Zürich. Klinik für Geriatrie' => [ '11221' ],
	'Universitätsspital Zürich. Klinik für Gynäkologie' => [ '10174' ],
	'Universitätsspital Zürich. Klinik für Hämatologie. Bereich III, Departement für Innere Medizin' => [ '10032' ],
	'Universitätsspital Zürich. Klinik für Immunologie' => [ '10033' ],
	'Universitätsspital Zürich. Klinik für Infektionskranheiten und Spitalhygiene' => [ '10234' ],
	'Universitätsspital Zürich. Klinik für Infektionskrankheiten und Spitalhygiene' => [ '10234' ],
	'Universitätsspital Zürich. Klinik für Kardiologie' => [ '10209' ],
	'Universitätsspital Zürich. Klinik für Kardiologie, Rhythmologie/Devices' => [ '10209' ],
	'Universitätsspital Zürich. Klinik für Klinische Pharmakologie und Toxikologie' => [ '10199' ],
	'Universitätsspital Zürich. Klinik für Konsiliarpsychiatrie und Psychosomatik' => [ '10057' ],
	'Universitätsspital Zürich. Klinik für Medizinische Onkologie und Hämatologie' => [ '10032' ],
	'Universitätsspital Zürich. Klinik für Mund-, Kiefer- und Gesichtschirurgie' => [ '10069' ],
	'Universitätsspital Zürich. Klinik für Neonatologie' => [ '10027' ],
	'Universitätsspital Zürich. Klinik für Nephrologie' => [ '10035' ],
	'Universitätsspital Zürich. Klinik für Neurochirurgie' => [ '10180' ],
	'Universitätsspital Zürich. Klinik für Neurologie' => [ '10040' ],
	'Universitätsspital Zürich. Klinik für Nuklearmedizin' => [ '10181' ],
	'Universitätsspital Zürich. Klinik für Ohren-, Nasen-, Hals- und Gesichtschirurgie' => [ '10045' ],
	'Universitätsspital Zürich. Klinik für Otorhinolaryngologie' => [ '10045' ],
	'Universitätsspital Zürich. Klinik für Plastische Chirurgie und Handchirurgie' => [ '10266' ],
	'Universitätsspital Zürich. Klinik für Pneumologie' => [ '10178' ],
	'Universitätsspital Zürich. Klinik für Psychiatrie und Psychotherapie' => [ '10057' ],
	'Universitätsspital Zürich. Klinik für Radio-Onkologie' => [ '10044' ],
	'Universitätsspital Zürich. Klinik für Reproduktions-Endokrinologie' => [ '10175' ],
	'Universitätsspital Zürich. Klinik für Rheumatologie' => [ '10051' ],
	'Universitätsspital Zürich. Klinik für Thoraxchirurgie' => [ '10255' ],
	'Universitätsspital Zürich. Klinik für Traumatologie' => [ '10021' ],
	'Universitätsspital Zürich. Klinik für Unfallchirurgie' => [ '10021' ],
	'Universitätsspital Zürich. Klinik für Urologie' => [ '10062' ],
	'Universitätsspital Zürich. Klinik für Viszeral- und Transplantationschirurgie' => [ '10217' ],
	'Universitätsspital Zürich. Klinik und Poliklinik für Innere Medizin' => [ '10029' ],
	'Universitätsspital Zürich. Klinik und Poliklinik für Nuklearmedizin' => [ '10181' ],
	'Universitätsspital Zürich. Klinik und Polyklinik für Innere Medizin' => [ '10029' ],
	'Universitätsspital Zürich. Universitäres Herzzentrum' => [ '10209' ],
	'Universitätsspital Zürich. Universitäres Herzzentrum Zürich. Klinik für Kardiologie' => [ '10209' ],
	'Universitätsspital Zürich. Zentrum für Hämatologie und Onkologie' => [ '10032' ],
	'Universitätsspital. Klinik für Traumatologie' => [ '10021' ],
	'Unversitätsklinik Balgrist. Klinik für Orthopädie' => [ '10046' ],
	'Veterinär-Anatomisches Institut' => [ '10077' ],
	'Veterinär-anatomisches Institut' => [ '10077' ],
	'Veterinäranatomisches Institut' => [ '10077' ],
	'Veterinärmdizinische Genetik' => [ '10187' ],
	'Veterinärmedizinisches Labor' => [ '11404' ],
	'Vetsuisse-Fakultät. Institut für Tierernährung' => [ '10227' ],
	'Virologisches Institut' => [ '10244' ],
	'Völkerkundemuseum Zürich' => [ '10246' ],
	'Zentrum für Zahn-, Mund- und Kieferheilkunde. Klinik für Präventivzahnmedizin, Parodontologie und Kariologie' => [ '10066' ],
	'Zentrum für Zahnmedizin Klinik für Präventivzahnmedizin, Parodontologie und Kariologie' => [ '10066' ],
	'Zentrum für Zahnmedizin. Klinik für Kieferorthopädie und Kinderzahnmedizin' => [ '10067' ],
	'Zentrum für Zahnmedizin. Klinik für Kronen- und Brückenprothetik, Teilprothetik und zahnärztliche Materialkunde' => [ '10068' ],
	'Zentrum für Zahnmedizin. Klinik für Mund-, Kiefer- und Gesichtschirurgie' => [ '10069' ],
	'Zentrum für Zahnmedizin. Klinik für Mund-, Kiefer- und Gesichtschirurgie - Klinik für Oralchirurgie' => [ '10069' ],
	'Zentrum für Zahnmedizin. Klinik für Präventivzahnmedizin, Parodontologie und Kariologie' => [ '10066' ],
	'Zentrum für Zahnmedizin. Klinik für Präventivzahnmedizin, Parodontologie und Kariologie (PPK)' => [ '10066' ],
};

#
# Filter definitions (regex) for various MARC data. Must come from data analysis of 
# a batch of MARC records
# Attention: Non-ASCII (> ASCII 127) must be encoded with \x{hex}, otherwise the regex will
# run into a memory error
#
# creators filter (245_c field with ancient cataloging rules)
$c->{marcfilter}->{creators} = [
	'^apresentada\spor\s',
	'^by\s',
	'^da\s',
	'^eingereicht\svon\s',
	'^par\s',
	'^por\s',
	'^pres\.\sby\s',
	'^presentada\spor\s',
	'^presented\sby\s',
	'^presented\sby',
	'^pr\x{e9}sent\x{e9}e\spar\s',
	'^submitted\sby\s',
	'^verfasst\svon\s',
	'^vergelegt\s\[i\.e\.\svorgelegt]\s',
	'^von\s',
	'^vorgelegt\svon\slic\.\sphil\.\s',
	'^vorgelegt\s\[von]\s',
	'^vorgelegt\svon\s',
	'^vorgelegt\svon:\s+',
	',$',
	'\s\.\.\.\s\[et\sal\.\]',
	'^Verfasser:?\s',
	'^Verfasserin:?\s',
	'index\sof\sauthors:\s',
	'\s\[und\sviele\sweitere\]$',
];

# editors filter (245_c field with ancient cataloging rules)
# this filter isn't used with apply_filters, but for recognising editor role
$c->{marcfilter}->{editors} = [
	'\s\(Hg\.\)',
	'\s\(Hg\.\/dir\.\)',
	'^edited\sby\s',
	'^ed\.\sby\s',
	',\seditors?\.?$',
	'^herausgegeben\svon\s',
	'^Herausgegeben\svon\s',
	'\s\(Hrsg\.\)$',
	'\s\(eds\.\)\s*$',
	'\s\(Eds\.\)$',
	'\s\(Herausgeber\)\s*$',
	'\s\[Hrsg.\]\s*',
];

# examiners filter (502_a field)
$c->{marcfilter}->{examiners} = [
	'Ref\.:\s',
	'Ref\.\.\s',
	'Geb\.:\s',
	'Korref\.:\s',
	'Korref\.\.\s',
	'Koref\.:\s',
];

# pages filter

$c->{marcfilter}->{pages} = [
	',\s1\sCD-ROM',
	'1\sCD-ROM',
	'1\sBand',
	'1\sBd\.',
	'1\sOnline-Ressource\s?',
	'1\sonline\sresource\s?',
	'\d\svol\.',
	'\d\sBde\.',
	'\d\sB\x{e4}nde',
	'\d\sTeile',
	'\d\sparties',
	'\sSpalten',
	'\sungez\x{e4}hlte',
	'\sgez\x{e4}hlte',
	'^Circa\s',
	',\sAppendix',
	'\d+\sillus\.',
	'\sin\scolor\.?',
	'\sS\.',
	'\sSeiten',
	'\sSeite',
	'\sBl\.',
	'\sBl\x{e4}tter',
	'\s?p\.',
	'\(',
	'\)',
	'\[',
	'\]',
];

# filter for various "garbage"
$c->{marcfilter}->{garbage} = [
	'\[',
	']',
	',$',
	'^Imprint:\s',
	'\s2013$',
	'\x{a9}\s2018',
	'2005',
	'2015',
	'2017',
	'2018',
];

# filter for events
$c->{marcfilter}->{event} = [];

# filter for keywords
$c->{marcfilter}->{keywords} = [
	'\.$',
];

# filter for person names
$c->{marcfilter}->{person} = [
	',$',
];

# filter for series
$c->{marcfilter}->{series} = [
	'\s;$',
	',$',
];

# filter for funder names
$c->{marcfilter}->{funding} = [
	'Funded\s\by\s',
	'Sponsored\sby\s',
];

